import { useState } from 'react'
import { fmtDate, fmtTime, relativeDay } from '../domain/dates'
import { ROLES, roleLabel } from '../domain/lifecycle'
import { navigate } from '../router'
import { useApp } from '../store/store'
import { Badge, Button, Card, CardHead, EmptyState } from '../components/ui'

const KIND_LABEL: Record<string, { label: string; tone: string }> = {
  assignment: { label: 'Assignment', tone: 'info' },
  overdue: { label: 'Overdue', tone: 'late' },
  blocker: { label: 'Blocker', tone: 'bad' },
  approval_request: { label: 'Approval requested', tone: 'warn' },
  approval_result: { label: 'Decision', tone: 'ok' },
  scope: { label: 'Scope change', tone: 'warn' },
  status: { label: 'Status', tone: 'muted' },
}

export function NotificationsScreen() {
  const { db, role, run } = useApp()
  const [scope, setScope] = useState<'mine' | 'all'>('mine')
  const list = db.notifications.filter((n) => (scope === 'mine' ? n.audienceRoles.includes(role) : true))

  return (
    <div className="content" style={{ maxWidth: 940 }}>
      <div className="page-head">
        <div>
          <div className="eyebrow">Notification centre</div>
          <h1 className="h1">What the system told people</h1>
          <p className="muted small" style={{ marginTop: 4 }}>
            In-app notifications are generated by project events. Email would carry the same payload as a secondary
            channel.
          </p>
        </div>
        <span className="spacer" />
        <div className="seg">
          <button className={scope === 'mine' ? 'on' : ''} onClick={() => setScope('mine')}>
            For {roleLabel(role)}
          </button>
          <button className={scope === 'all' ? 'on' : ''} onClick={() => setScope('all')}>
            All roles
          </button>
        </div>
        <Button onClick={() => run({ type: 'read_all_notifications' })}>Mark all read</Button>
      </div>

      <Card>
        <CardHead title={`${list.length} notifications`} sub={`${list.filter((n) => !n.read).length} unread`} />
        <div>
          {list.length === 0 && <EmptyState title="No notifications" body="Actions on projects generate notifications here." />}
          {list.map((n) => (
            <div
              key={n.id}
              className={`notif ${n.read ? 'read' : 'unread'}`}
              onClick={() => {
                run({ type: 'read_notification', id: n.id })
                if (n.href) navigate(n.href)
              }}
            >
              <span className="nd" aria-hidden />
              <div style={{ minWidth: 0, flex: 1 }}>
                <div className="row wrap" style={{ gap: 8 }}>
                  <span className="nt">{n.title}</span>
                  <Badge tone={KIND_LABEL[n.kind]?.tone ?? 'muted'}>{KIND_LABEL[n.kind]?.label ?? n.kind}</Badge>
                </div>
                <div className="nb">{n.body}</div>
                <div className="nw">
                  {relativeDay(n.at, db.today)} {fmtTime(n.at)} · sent to{' '}
                  {n.audienceRoles.map((r) => roleLabel(r)).join(', ')}
                </div>
              </div>
            </div>
          ))}
        </div>
      </Card>
    </div>
  )
}
